In [2]:
import pandas as pd
import numpy as np
import os

In [2]:
survey_blood_file = '/Users/jerenolsen/Desktop/PGP_Harvard_data/Surveys/All Combined/Blood'

In [3]:
ehr_test_results_file = '/Users/jerenolsen/Desktop/PGP_Harvard_data/EHRS/All Combined/test_results'
ehr_conditions = '/Users/jerenolsen/Desktop/PGP_Harvard_data/EHRS/All Combined/conditions'

In [4]:
blood_df = pd.read_csv(survey_blood_file, delimiter = '\t')
test_results_df = pd.read_csv(ehr_test_results_file, delimiter = '\t')
conditions = pd.read_csv(ehr_conditions, delimiter = '\t')

In [5]:
len(test_results_df['profile_id'].unique())

335

In [6]:
iron_def_ehr = conditions[conditions['Name'].str.contains('Iron') == True]
print(len(iron_def_ehr))

3

In [7]:
blood_df.rename(columns = {'Have you ever been diagnosed with any of the following conditions?':'conditions'}, inplace=True)
blood_df.replace(np.nan,'',regex=True, inplace=True) 
blood_df['conditions'] = blood_df['conditions'].apply(str.lower)
iron_survey = blood_df[blood_df['conditions'].str.contains('iron')]

In [8]:
iron_survey.head()

,Unnamed: 0,profile_id,provider_id,conditions,Other condition not listed here?,PGP Trait & Disease Survey 2012: Blood,Timestamp
0,0,hu005023,23andMe,iron deficiency anemia,,Responses submitted 8/4/2013 21:55:50. Show r...,8/4/2013 21:55:50
4,4,hu024B5D,23andMe,iron deficiency anemia,hemochromatosis,Responses submitted 3/2/2014 12:11:01. Show r...,3/2/2014 12:11:01
6,6,hu025CEA,23andMe,iron deficiency anemia,,Responses submitted 3/27/2013 13:05:12. Show ...,3/27/2013 13:05:12
10,10,hu034DB1,23andMe,iron deficiency anemia,,Responses submitted 11/9/2012 8:25:31. Show r...,11/9/2012 8:25:31
13,13,hu05CA34,23andMe,iron deficiency anemia,,Responses submitted 5/9/2013 6:46:00. Show re...,5/9/2013 6:46:00

In [9]:
blood_df.head()

,Unnamed: 0,profile_id,provider_id,conditions,Other condition not listed here?,PGP Trait & Disease Survey 2012: Blood,Timestamp
0,0,hu005023,23andMe,iron deficiency anemia,,Responses submitted 8/4/2013 21:55:50. Show r...,8/4/2013 21:55:50
1,1,hu00698E,23andMe,,,Responses submitted 10/8/2014 16:47:02. Show ...,10/8/2014 16:47:02
2,2,hu011C57,23andMe,,,Responses submitted 10/13/2012 1:36:10. Show ...,10/13/2012 1:36:10
3,3,hu016B28,23andMe,,,Responses submitted 10/25/2012 13:13:59. Show...,10/25/2012 13:13:59
4,4,hu024B5D,23andMe,iron deficiency anemia,hemochromatosis,Responses submitted 3/2/2014 12:11:01. Show r...,3/2/2014 12:11:01

In [10]:
print(len(iron_survey))
iron_survey.head()

137

,Unnamed: 0,profile_id,provider_id,conditions,Other condition not listed here?,PGP Trait & Disease Survey 2012: Blood,Timestamp
0,0,hu005023,23andMe,iron deficiency anemia,,Responses submitted 8/4/2013 21:55:50. Show r...,8/4/2013 21:55:50
4,4,hu024B5D,23andMe,iron deficiency anemia,hemochromatosis,Responses submitted 3/2/2014 12:11:01. Show r...,3/2/2014 12:11:01
6,6,hu025CEA,23andMe,iron deficiency anemia,,Responses submitted 3/27/2013 13:05:12. Show ...,3/27/2013 13:05:12
10,10,hu034DB1,23andMe,iron deficiency anemia,,Responses submitted 11/9/2012 8:25:31. Show r...,11/9/2012 8:25:31
13,13,hu05CA34,23andMe,iron deficiency anemia,,Responses submitted 5/9/2013 6:46:00. Show re...,5/9/2013 6:46:00

In [11]:
blood_profiles_1 = iron_survey['profile_id'].unique().tolist()
blood_profiles_2 = iron_def_ehr['profile_id'].unique().tolist()
blood_profiles_2 = [p for p in blood_profiles_2 if p not in blood_profiles_1]
print(len(blood_profiles_1))
print(len(blood_profiles_2))

137
0

In [12]:
# 1. Get demographics summary of blood profiles
# 2. Check if metablomics / test results are available for blood profiles

# Iron deficient participants with relevant test_results (there are only 2)

In [13]:
test_results_df = test_results_df[test_results_df['profile_id'].isin(blood_profiles_1)]

In [14]:
print(len(test_results_df['profile_id'].unique()))
test_results_df.head()

45

,Unnamed: 0,profile_id,sequence_provider,Name,Result,Date
333,333,huD4F7DB,23andMe,TB Skin Test,0 mm,2010-03-19
334,334,huD4F7DB,23andMe,Weight,140 lb,2011-05-20
335,335,huD4F7DB,23andMe,Height,67 in,2011-05-24
380,380,huC4A276,23andMe,Height,71 inches,2009-10-11
381,381,huC4A276,23andMe,Height,71 inches,2009-10-11

In [15]:
all_markers = test_results_df['Name'].unique().tolist()
all_markers

['TB Skin Test',
 'Weight',
 'Height',
 'ALT (SGPT)',
 'wbc',
 'Immature Grans (Abs)',
 'Glucose, serum',
 'Thyroid Peroxidase (TPO) Ab',
 'Triiodothyronine (T3)',
 'Thyroglobulin, Antibody',
 'VITAMIN B12',
 'T4,Free(Direct)',
 'TSH',
 'Insulin',
 'Immature Granulocytes',
 'Hemoglobin A1C',
 'Cholesterol, Total',
 'Vitamin D, 25-hydroxy',
 'Occult Blood, Fecal, IA',
 'LDL Cholesterol Calc',
 'Sedimentation Rate-Westergren',
 'Albumin, Serum',
 'Lymphs',
 'Glucose, Plasma',
 'Globulin, total',
 'Creatinine, Serum',
 'INR',
 'Creatine Kinase,Total,Serum',
 'BUN',
 'hCG,Beta Subunit,Qual,Serum',
 'H1N1 LAIV Vaccine Product Specific Considerations',
 'Indications for deferring vaccination',
 '2nd pneumovax dose Administered',
 'Date 1st pneumovax dose Administered',
 'Pneumonia Vaccine Contraindications',
 'Pneumonia Vaccination Indications',
 'Influenza Vaccine Product Specific Considerations',
 'H1N1 Vaccination Indications',
 'Vaccine Consent Complete',
 'Upper Respiratory Culture',
 'TRIGLYCERIDES',
 'Hematocrit',
 'Thyroxine (T4), Free - Serum',
 'Triiodothyronine (T3), Free - Serum',
 'Thyroid Stimulating Hormone (TSH)',
 'Protein, Total, Serum',
 'Methylmalonic Acid, Serum',
 'Diastolic Blood Pressure',
 'Systolic Blood Pressure',
 'Alkaline Phosphatase',
 'Aspartate Aminotransferase (AST)',
 'Basophils - Blood',
 'Bilirubin, Total',
 'Blood Urea Nitrogen (BUN)',
 'Calcium, Serum',
 'Carbon Dioxide - Serum',
 'Chloride, Serum',
 'White Blood Cell (WBC) Count',
 'Alanine Transaminase (ALT)',
 'Eosinophil Count, Blood',
 'Glucose - Plasma',
 'HDL Cholesterol',
 'Very Low Density Lipoprotein (VLDL) Cholesterol',
 'Hemoglobin - Blood',
 'LDL Cholesterol',
 'Triglycerides, Blood',
 'Mean Corpuscular Hemoglobin (MCH)',
 'Mean Corpuscular Hemoglobin Concentration (MCHC)',
 'Mean Corpuscular Volume (MCV)',
 'Monocytes - Blood',
 'Neutrophils - Blood',
 'Platelet Count',
 'Potassium, Serum',
 'RDW',
 'Red Blood Cell (RBC) Count',
 'Sodium, Blood',
 'Urine Specific Gravity',
 'Urine pH',
 'Total Protein',
 'Lymphocytes - Blood',
 '25-Hydroxy Vitamin D',
 'Exercise Stress Test',
 'Free Thyroxine Index: calc',
 'Genotype FABP2 (+ 1283)',
 'Genotype PPARG (+34)',
 'Genotype ADRB3 (+190)',
 'Genotype ADRB2 (+79)',
 'Genotype ADRB2 (+46)',
 'A:G Ratio',
 'ALBUMIN',
 'Alk Phos',
 'Basos',
 'Bilirubin total',
 'CALCIUM',
 'Cholesterol, Total (Fasting)',
 'CL',
 'CO2',
 'CREATININE',
 'Triglycerides (Fasting)',
 'Eos',
 'Abs menos',
 'Abs lymphs',
 'Abs eos',
 'Abs neuts',
 'Abs basos',
 'GFR non African Amer',
 'Globulin (calc)',
 'GLUCOSE',
 'Serum Glutamic-Oxaloacetic Transaminase (SGOT)',
 'HDL (Fasting)',
 'Hgb (from CBC)',
 'SGPT',
 'K',
 'LDL (clc)',
 'Monos',
 nan,
 'Neuts',
 'PLT',
 'Protein',
 'Hct (from CBC)',
 'Hours slept',
 'colposcopy',
 'human papilloma virus',
 'Hemoglobin A1c (HbA1c)',
 'C-reactive Protein (CRP)',
 'arup test code',
 'final',
 'Glucose [Mass/volume] in Serum or Plasma',
 'Ceruloplasmin [Mass/volume] in Serum or Plasma',
 'Copper [Mass/volume] in Blood',
 'Laboratory Studies',
 'Phospholipids, Serum',
 'Homocyst(e)ine, Plasma',
 'Result 1',
 'Folate (Folic Acid), serum',
 'Glucose, 2 hour',
 'Factor V Leiden Mutation',
 'Triiodothyronine,Free,Serum',
 'Lyme IgM WB Interp.',
 'Thyroxine (T4)',
 'Heart rate',
 'Body temperature',
 'Blood Sugar',
 'Blood glucose',
 'Cycling time',
 'Cycling distance',
 'SPECIFIC GRAVITY',
 'Hemoglobin ALC',
 'Sedimentation Rate',
 'H. pylori Breath Test',
 'Cortisol - AM',
 'C-Reactive Protein, Cardiac',
 'ANA Direct',
 'Pregnenolone, MS',
 'DHEA-Sulfate',
 'HBsAg Screen',
 'HCV Ab',
 'Hep B Core Ab, Tot',
 'Hep B Surface Ab',
 'Lipoprotein-a (Lp(a))',
 'Homocysteine - Serum',
 'Taurine',
 'Methylmalonic Acid Test',
 'Phosphoethanolamine',
 'Globulin - Serum',
 'ALT/SGPT',
 'Creatine Phosphokinase (CPK)',
 'TSH Receptor Antibody',
 'AST/SGOT',
 'Glomerular Filtration Rate (GFR), Predicted',
 'Bicarbonate - Serum',
 'Bilirubin, Direct',
 'Bilirubin, Indirect',
 'Glucose, Fasting - Plasma',
 'Apolipoprotein A',
 'Apolipoprotein B100 (ApoB100)',
 'Eos (Absolute)',
 'Baso (Absolute)',
 'Neutrophils (Absolute)',
 'Lymphs (Absolute)',
 'Monocytes (Absolute)',
 'Linoleic LA',
 'HDL2',
 'Lp-PLA',
 'NT-proBNP',
 'Omega-3 Total',
 'LDL-P',
 'Insulin, Serum',
 'HS-Omega-3 Index (RBC EPA + DHA)',
 'Saturated Fatty Acids Total',
 'sdLDL',
 'Myeloperoxidase Antibody - Serum',
 'HDL-P',
 'HbA1c',
 'Galectin-3',
 'Free Fatty Acid',
 'ALA Alpha-Linolenic',
 'Fibrinogen',
 'Trans Fatty Acids Total',
 'Eicosapentaenoic EPA',
 'Eiconsapentaenoic EPA',
 'Arachidonic AA',
 'Docosahexaenoic DHA',
 'CK',
 'cis-Monounsaturated Fatty Acids Total',
 'C-Reactive Protein, High Sensitivity (hsCRP)',
 'Vitamin B12 Level',
 'ALP',
 'APB:APO A-1 Ratio (calculated)',
 'DPA Docosapentaenoic',
 'Folate - RBC',
 'CHLORIDE',
 'SODIUM',
 'Cholesterol, HDL - Serum',
 'Cholesterol, LDL - Serum',
 'POTASSIUM',
 'PROTEIN, TOTAL',
 'AST',
 'Triglycerides - Plasma',
 'ALT',
 'Growth Hormone (GH)',
 'Triiodothyronine (T3), Reverse - Serum',
 'Human Growth Hormone (HGH) - Serum',
 'Prolactin (PRL)',
 'MCHC',
 'RDW-CV',
 'Hemoglobin',
 'Lyme Disease Antibody',
 'MCV',
 'ACA IgM',
 'RBC',
 'ACA IgG',
 'ACA IgA',
 'MCH',
 'Antinuclear Antibody (ANA), Titer - Serum',
 'Abs Neut (ANC)',
 'Abs Mono',
 'Osmolality, Serum',
 'Abs Lymph',
 'Abs Eosin',
 'Abs Baso',
 'Borrelia Burgdorferi Total Antibodies - CSF',
 'Prothrombin Activity',
 'International Normalized Ratio (INR) - Blood',
 'Cerebrospinal Fluid (CSF) Total Protein',
 'Cerebrospinal Fluid (CSF) Glucose',
 'Cerebrospinal Fluid (CSF) Oligoclonal Banding',
 'Lymph%',
 'HBsAg',
 'mpv',
 'Baso%',
 'Mono%',
 'Neut%',
 'Anion Gap',
 'Eosin%',
 'Gamma Globulin',
 'Gamma Globulin, Ur',
 'Beta Globulin, Ur',
 'Alpha 1 Globulin, Ur',
 'Beta Globulin',
 'Alpha 2 Globulin, Ur',
 'Alpha 2 Globulin',
 'Alpha 1 Globulin',
 'Aldosterone - Serum',
 'Progesterone, Serum',
 'Renin - Serum',
 'Estradiol, Serum',
 'Staff Review, MPA',
 'MPA Serum IgA',
 'MPA Serum IgM',
 'MPA Serum IgG',
 'MPA Kappa/Lambda Rat',
 'HGB',
 'Eldoncard 2511',
 'Iron, Serum',
 'Fat Mass',
 'Systolic Pressure',
 'Diastolic Pressure',
 'Antinuclear Antibody (ANA)',
 'Smith Extractable Nuclear Antibody - Serum',
 'Extractable Nuclear Antigen',
 'Sleep Study',
 'HLA-B27 Antigen',
 'HSV-1',
 "Prometheus Panel Crohn's & Celiac's",
 'Eye Exam',
 'Foot exam',
 'Partial thromboplastin time, activated',
 'ALT (Alanine aminotransferase test)',
 'INR (Prothrombin time)',
 'Creatine kinase measurement',
 'AST (Aspartate aminotransferase test)',
 'Troponin',
 'BNP (Brain natriuretic peptides test)',
 'Myoglobin measurement',
 'Prothrombin Time',
 'mammogram',
 'colonoscopy',
 'eGFR If NonAfricn Am',
 'RA Latex Turbid.',
 'Cryoglobulin, Ql, Serum, Rflx',
 "Sjogren's Anti-SS-A",
 'Complement C4, Serum',
 'Creatinine, Urine',
 'RNP Antibodies',
 'C-Reactive Protein, Quant',
 'Anti-DNA (DS) Ab Qn',
 'PTH, Intact',
 'Complement C3, Serum',
 'Chloride, Urine',
 'Creatine',
 'Potassium, Urine',
 'Glucose, Blood',
 'Hemoglobin, Serum',
 'Erythropoietin (EPO), Serum',
 'Iron Binding Capacity, Unsaturated - Serum',
 'Total Iron Binding Capacity (TIBC)',
 'Calcium, Urine',
 'Triglycerides, Fasting - Serum',
 'Electrocardiogram (ECG)',
 'Ferritin, Serum',
 'Urine Calcium',
 'Parathyroid Hormone (PTH)',
 'Folate',
 'Pulse',
 'Blood Pressure, Diastolic (Lower Number)',
 'Blood Pressure, Systolic (Upper Number)',
 'Vitamin D3, 25-OH (Calcifediol)',
 'Protein, Urine',
 'Testosterone, Serum',
 'DHEA-Sulfate, Serum',
 'bone density',
 'Lipid Profile',
 'Steps taken',
 'billirubin total',
 'PT INR',
 'IGG, Urine, Electrophorisis',
 'Complement Component 3 (C3)',
 'Complement Component 4 (C4)',
 'creatinine 24 hour urine',
 'Uric Acid, Serum',
 'Protein, Quantitative, 24 urine',
 'IgA, Urine, Electrophorisis',
 'IGM, Urine, Electrophorisis',
 'Magnesium, Serum',
 'Phosphorous',
 'Mass Cell Volume',
 'Prothrombin Time on Whole Blood',
 'High-Density Lipoprotein (HDL)',
 'Low-Density Lipoprotein (LDL)',
 'Glomerular Filtration Rate (GFR)',
 'lipoprotein Associated Phospholiase A2',
 'Serum Glutamate Pyruvate Transaminase (SGPT)',
 'MRI',
 'Cardiac echo',
 'Cardiac enzymes',
 'Chest x-ray',
 'EKC 12 lead',
 'Ultrasound of legs',
 'Vitamin D3 (Cholecalciferol) - Serum']

In [16]:
biomarkers = ['Serum ferritin', 'ferritin', 'serum iron', 'transferrin', 'erythrocyte', 'zinc', 'ZPP/H', 'hepicidin']
#Serum ferritin #1
# serum iron, transferrin and ferritin
# erythrocyte zinc-protoporphyrin/heme ratio (ZPP/H) and serum hepcidin measurements.

In [17]:
all_markers = [marker for marker in all_markers if type(marker) != float]
present_markers1 = [marker for marker in all_markers if 'iron' in marker.lower()]
present_markers2 = [marker for marker in all_markers if 'ferritin' in marker.lower()]

In [18]:
iron_biomarkers = present_markers1+present_markers2
iron_biomarkers

['Iron, Serum',
 'Iron Binding Capacity, Unsaturated - Serum',
 'Total Iron Binding Capacity (TIBC)',
 'Ferritin, Serum']

In [19]:
test_results_df = test_results_df[test_results_df['Name'].isin(iron_biomarkers)]

In [20]:
print(len(test_results_df['profile_id'].unique()))

2

In [21]:
test_results_df.head(20)

,Unnamed: 0,profile_id,sequence_provider,Name,Result,Date
13190,13190,huB2C416,23andMe,"Iron, Serum",8.2,2011-03-03
16322,16322,hu2D6140,CG,"Iron Binding Capacity, Unsaturated - Serum",4,2005-06-30
16323,16323,hu2D6140,CG,"Iron, Serum",19,2005-06-30
16325,16325,hu2D6140,CG,Total Iron Binding Capacity (TIBC),461,2005-06-30
16382,16382,hu2D6140,CG,"Ferritin, Serum",8,2007-12-28
16404,16404,hu2D6140,CG,Total Iron Binding Capacity (TIBC),371,2008-06-16
16405,16405,hu2D6140,CG,"Ferritin, Serum",10,2008-06-16
16407,16407,hu2D6140,CG,"Iron, Serum",60,2008-09-25
16409,16409,hu2D6140,CG,Total Iron Binding Capacity (TIBC),330,2008-09-25
16430,16430,hu2D6140,CG,"Ferritin, Serum",36,2009-01-09
16436,16436,hu2D6140,CG,"Ferritin, Serum",37,2009-05-29

# Iron deficient Participants Demographics
Want:
    - Age
    - Gender
    - Race
    - Blood type

In [22]:
demo_surveys = '/Users/jerenolsen/Desktop/PGP_Harvard_data/Surveys/All Combined/Participant Survey'
demo_ehr = '/Users/jerenolsen/Desktop/PGP_Harvard_data/EHRS/All Combined/demographics'

In [23]:
demo_surveys  = pd.read_csv(demo_surveys, delimiter = '\t')
demo_ehr = pd.read_csv(demo_ehr, delimiter = '\t')

In [24]:
demo_surveys = demo_surveys[demo_surveys['profile_id'].isin(blood_profiles_1)]
#[print(item) for item in demo_surveys.columns.tolist()]

In [39]:
demo_surveys_sub = demo_surveys[['profile_id', 'Sex/Gender','Race/ethnicity', 'Year of birth']]
demo_surveys_sub.rename(columns = {'Year of birth': 'Date of Birth', 'Race/ethnicity': 'Race', 'Sex/Gender':'Gender' }, inplace = True)
demo_surveys_sub.head()
demo_surveys_sub['Gender'].value_counts()

/var/folders/7s/_bh70s2n68zd14b4fsfcjcv00000gn/T/ipykernel_21853/3736424525.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  demo_surveys_sub.rename(columns = {'Year of birth': 'Date of Birth', 'Race/ethnicity': 'Race', 'Sex/Gender':'Gender' }, inplace = True)

Female               107
Male                  19
genderqueer            1
neutrois, agender      1
Name: Gender, dtype: int64

In [37]:
demo_ehr = demo_ehr[demo_ehr['profile_id'].isin(blood_profiles_1)]

In [38]:
demo_ehr_sub = demo_ehr[['profile_id', 'Date of Birth','Race','Gender', 'Blood Type']]
demo_ehr_sub['Gender'].value_counts()

Female    31
Male       6
Name: Gender, dtype: int64

In [28]:
demo_ehr_sub.reset_index(drop=True, inplace = True)
demo_ehr_sub.head()

  profile_id              Date of Birth   Race  Gender Blood Type
0   huD4F7DB  1976-02-15 (47 years old)  White  Female         A+
1   huC4A276  1967-04-22 (55 years old)  White  Female         A-
2   hu48C4EB  1984-03-26 (38 years old)  White    Male         A+
3   hu925B56  1958-03-27 (64 years old)    NaN     NaN        NaN
4   huF421B2  1951-01-04 (72 years old)    NaN     NaN        NaN

In [29]:
# Impute missing values from ehr demographics using survey demographics

In [30]:
impute_list = ['Date of Birth', 'Race', 'Gender']
for i, row in demo_ehr_sub.iterrows():
    for col in impute_list:
        profile_id = row['profile_id']
        val = row[col]
        if type(val) == float:
            new_val = demo_surveys_sub[demo_surveys_sub['profile_id'] == profile_id][col].values[0]
            demo_ehr_sub.iloc[i][col] = new_val

In [31]:
demo_ehr_sub.head()

  profile_id              Date of Birth   Race  Gender Blood Type
0   huD4F7DB  1976-02-15 (47 years old)  White  Female         A+
1   huC4A276  1967-04-22 (55 years old)  White  Female         A-
2   hu48C4EB  1984-03-26 (38 years old)  White    Male         A+
3   hu925B56  1958-03-27 (64 years old)  White  Female        NaN
4   huF421B2  1951-01-04 (72 years old)  White  Female        NaN

In [32]:
# Combine EHR demographics with survey demographics, excluding profile_ids from survey demographics that
    #are already present in ehr

In [33]:
profile_ids = demo_ehr_sub['profile_id'].tolist()
print(len(demo_surveys_sub))
demo_surveys_sub = demo_surveys_sub[demo_surveys_sub['profile_id'].isin(profile_ids) == False]
print(len(demo_surveys_sub))

130
75

In [34]:
iron_demographics = pd.concat([demo_ehr_sub,demo_surveys_sub])
iron_demographics.reset_index(drop=True, inplace = True)
iron_demographics

    profile_id              Date of Birth   Race  Gender Blood Type
0     huD4F7DB  1976-02-15 (47 years old)  White  Female         A+
1     huC4A276  1967-04-22 (55 years old)  White  Female         A-
2     hu48C4EB  1984-03-26 (38 years old)  White    Male         A+
3     hu925B56  1958-03-27 (64 years old)  White  Female        NaN
4     huF421B2  1951-01-04 (72 years old)  White  Female        NaN
..         ...                        ...    ...     ...        ...
126   hu87BAAD                       1941  White  Female        NaN
127   hu8B2C08                21-29 years  White  Female        NaN
128   huA06085                       1980  White  Female        NaN
129   huD649F1                       1951  White  Female        NaN
130   huFFB09D                40-49 years  White  Female        NaN

[131 rows x 5 columns]

In [35]:
iron_demographics['Race'].value_counts()

White                                                                       115
Hispanic or Latino, White                                                     3
Hispanic or Latino                                                            2
American Indian / Alaska Native, Hispanic or Latino, White                    2
Black or African American                                                     2
American Indian or Alaska Native                                              1
Hispanic/Latino                                                               1
No response                                                                   1
American Indian / Alaska Native, White, No response                           1
American Indian / Alaska Native, Asian, Black or African American, White      1
American Indian / Alaska Native, White                                        1
Name: Race, dtype: int64

In [36]:
iron_demographics['Gender'].value_counts()

Female               108
Male                  19
neutrois, agender      1
genderqueer            1
Name: Gender, dtype: int64

In [40]:
iron_demographics['Blood Type'].value_counts()

O+     13
A+      9
B+      4
A-      3
O-      2
AB-     1
B-      1
Name: Blood Type, dtype: int64

In [41]:
blood_profiles_1

['hu005023',
 'hu024B5D',
 'hu025CEA',
 'hu034DB1',
 'hu05CA34',
 'hu066C78',
 'hu09D626',
 'hu0B4CF6',
 'hu0B51B8',
 'hu0FDE6C',
 'hu101EF8',
 'hu11603C',
 'hu1187FF',
 'hu14262A',
 'hu1712BC',
 'hu1843FC',
 'hu24A473',
 'hu250634',
 'hu28391C',
 'hu313730',
 'hu340C7A',
 'hu35E970',
 'hu36A660',
 'hu392622',
 'hu3B032D',
 'hu3C0611',
 'hu3DC5EA',
 'hu3E9D3B',
 'hu3F37F2',
 'hu3F864B',
 'hu43294F',
 'hu48C4EB',
 'hu4B11A3',
 'hu4B3CE7',
 'hu4B3FF4',
 'hu4B41E2',
 'hu4C20BC',
 'hu4D8786',
 'hu4D906B',
 'hu4F45FB',
 'hu50B3F5',
 'hu52E130',
 'hu52F6FF',
 'hu536A4B',
 'hu54EA88',
 'hu5C3F07',
 'hu6036FB',
 'hu60EF43',
 'hu627574',
 'hu6368DD',
 'hu689E16',
 'hu691345',
 'hu6B7829',
 'hu6D1115',
 'hu6D50BE',
 'hu6F6F6C',
 'hu6FECE9',
 'hu70552D',
 'hu72076D',
 'hu79FC40',
 'hu7A03F2',
 'hu7A2F1D',
 'hu7DE7FD',
 'hu7FC773',
 'hu80AD0F',
 'hu851AB8',
 'hu8602F1',
 'hu87223B',
 'hu8BF030',
 'hu8CF9E7',
 'hu9122D5',
 'hu925B56',
 'hu945E6C',
 'hu979849',
 'hu9AE5EE',
 'huA110DA',
 'huA2CA68',
 'huA2D79E',
 'huA8DD58',
 'huA9AFFD',
 'huAC3640',
 'huAC9980',
 'huAD6C57',
 'huAF3C63',
 'huB173FD',
 'huB19789',
 'huB2C416',
 'huB90F20',
 'huBC03A7',
 'huBC4E20',
 'huC3ACB0',
 'huC434ED',
 'huC4A276',
 'huCFF045',
 'huD37D14',
 'huD4F7DB',
 'huD50F73',
 'huD58ABC',
 'huD76A20',
 'huDBDF82',
 'huDD5D00',
 'huDDCF88',
 'huDF9008',
 'huE07725',
 'huE18D82',
 'huEBFE01',
 'huEFD2F0',
 'huF421B2',
 'huF629AC',
 'huF6CDC1',
 'huF9A043',
 'huFC361A',
 'huFD4AD3',
 'huFF6AB4',
 'hu040C0A',
 'hu24C863',
 'hu2D6140',
 'hu342A08',
 'hu397733',
 'hu3E50D4',
 'hu5A063B',
 'hu5FA322',
 'hu60180F',
 'hu602487',
 'hu687B6B',
 'hu72A81D',
 'hu802D92',
 'hu87BAAD',
 'hu8B2C08',
 'hu8E87A9',
 'huA06085',
 'huA0E089',
 'huA5BEB9',
 'huAA245C',
 'huAC887E',
 'huD649F1',
 'huFFB09D']

In [43]:
conditions_sub = conditions[conditions['profile_id'].isin(blood_profiles_1)]

In [45]:
conditions_sub['Name'].value_counts()

DEPRESSION                            7
Urinary Tract Infection (UTI)         5
Shingles                              5
ASTHMA                                5
Astigmatism                           4
                                     ..
Ice cream headaches                   1
Homocystinuria                        1
High blood triglycerides              1
Hiccups                               1
Basal cell of skin - face and arms    1
Name: Name, Length: 429, dtype: int64

In [52]:
base_dir = '/Users/jerenolsen/Desktop/PGP_Harvard_data/Surveys/All Combined/'
comorbidities = {}
for survey_name in os.listdir(base_dir):
    print(file)
    survey_file = '/Users/jerenolsen/Desktop/PGP_Harvard_data/Surveys/All Combined/{}'.format(survey_name)
    df = pd.read_csv(survey_file, delimiter = '\t')
    df = df[df['profile_id'].isin(blood_profiles_1)]
    print(df.head())
    occurences = df[df.columns[3]].value_counts()
    comorbidities[survey_name] = occurences

Respiratory
    Unnamed: 0 profile_id provider_id  \
0            0   hu005023     23andMe
5            5   hu024B5D     23andMe
7            7   hu025CEA     23andMe
11          11   hu034DB1     23andMe
14          14   hu05CA34     23andMe

   Have you ever been diagnosed with one of the following conditions?  \
0                          Hyperopia (Farsightedness)
5   Myopia (Nearsightedness), Astigmatism, Meniere...
7                            Myopia (Nearsightedness)
11  Hyperopia (Farsightedness), Myopia (Nearsighte...
14              Myopia (Nearsightedness), Astigmatism

                  Other condition not listed here?  \
0                                              NaN
5                                              NaN
7                                              NaN
11  Color blind carrier, benign positional vertigo
14                                             NaN

   PGP Trait & Disease Survey 2012: Vision and hearing           Timestamp
0   Responses submitted 8/4/2013 21:56:46.  Show r...    8/4/2013 21:56:46
5   Responses submitted 3/2/2014 12:12:27.  Show r...    3/2/2014 12:12:27
7   Responses submitted 3/27/2013 13:06:53.  Show ...   3/27/2013 13:06:53
11  Responses submitted 11/9/2012 8:27:15.  Show r...    11/9/2012 8:27:15
14  Responses submitted 5/9/2013 6:40:44.  Show re...     5/9/2013 6:40:44
Respiratory
    Unnamed: 0 profile_id provider_id  \
0            0   hu005023     23andMe
4            4   hu024B5D     23andMe
6            6   hu025CEA     23andMe
10          10   hu034DB1     23andMe
13          13   hu05CA34     23andMe

   Have you ever been diagnosed with any of the following conditions?  \
0                                            Sciatica
4       Osteoarthritis, Bone spurs, Plantar fasciitis
6                                                 NaN
10             Sciatica, Achilles tendonitis, Bunions
13                     Achilles tendonitis, Scoliosis

   Other condition not listed here?  \
0                               NaN
4                        polio 1954
6      Discoid meniscus in one knee
10                              NaN
13                              NaN

   PGP Trait & Disease Survey 2012: Musculoskeletal System and Connective Tissue  \
0   Responses submitted 8/4/2013 22:00:19.  Show r...
4   Responses submitted 3/2/2014 12:22:15.  Show r...
6   Responses submitted 3/27/2013 13:40:24.  Show ...
10  Responses submitted 11/9/2012 8:32:36.  Show r...
13  Responses submitted 5/9/2013 6:50:00.  Show re...

             Timestamp
0    8/4/2013 22:00:19
4    3/2/2014 12:22:15
6   3/27/2013 13:40:24
10   11/9/2012 8:32:36
13    5/9/2013 6:50:00
Respiratory
    Unnamed: 0 profile_id provider_id  \
0            0   hu005023     23andMe
4            4   hu024B5D     23andMe
6            6   hu025CEA     23andMe
10          10   hu034DB1     23andMe
13          13   hu05CA34     23andMe

   Have you ever been diagnosed with any of the following conditions?  \
0                         Allergic contact dermatitis
4   Skin tags, Hair loss (includes female and male...
6                                                 NaN
10                                  Eczema, Skin tags
13                                                NaN

   Other condition not listed here?  \
0                               NaN
4           urticaria hives-chronic
6                               NaN
10                              NaN
13                              NaN

   PGP Trait & Disease Survey 2012: Skin and Subcutaneous Tissue  \
0   Responses submitted 8/4/2013 21:59:20.  Show r...
4   Responses submitted 3/2/2014 12:16:09.  Show r...
6   Responses submitted 3/27/2013 13:29:48.  Show ...
10  Responses submitted 11/9/2012 8:31:41.  Show r...
13  Responses submitted 5/9/2013 6:48:54.  Show re...

             Timestamp
0    8/4/2013 21:59:20
4    3/2/2014 12:16:09
6   3/27/2013 13:29:48
10   11/9/2012 8:31:41
13    5/9/2013 6:48:54
Respiratory
    Unnamed: 0 profile_id provider_id Anatomical sex at birth  \
2            2   hu005023     23andMe                     NaN
8            8   hu024B5D     23andMe                  Female
10          10   hu025CEA     23andMe                     NaN
14          14   hu034DB1     23andMe                     NaN
20          20   hu05CA34     23andMe                     NaN

   Are all your enrolled relatives linked to your PGP profile? Blood sample  \
2                                                 NaN                   Yes
8                                                 NaN                   NaN
10                                                NaN                   Yes
14                                                NaN                   Yes
20                                                NaN                   Yes

   Disease/trait: Diagnosis Disease/trait: Documentation  \
2                       NaN                          NaN
8                       NaN                          NaN
10                      NaN                          NaN
14                      NaN                          NaN
20                      NaN                          NaN

   Disease/trait: Documentation description  \
2                                       NaN
8                                       NaN
10                                      NaN
14                                      NaN
20                                      NaN

   Disease/trait: Genetic confirmation  ... Saliva sample  \
2                                  NaN  ...           Yes
8                                  NaN  ...           NaN
10                                 NaN  ...           Yes
14                                 NaN  ...           Yes
20                                 NaN  ...           Yes

   Severe disease or rare genetic trait Sex/Gender            Timestamp  \
2                                    No     Female  10/23/2011 23:21:20
8                                   NaN     Female    3/2/2014 12:08:01
10                                   No     Female   7/17/2011 21:56:02
14                                   No     Female   3/10/2013 16:10:20
20                                   No     Female     5/9/2013 5:40:28

   Tissue samples from autopsy Tissue samples from surgery  \
2                          Yes                         Yes
8                          NaN                         NaN
10                         Yes                         Yes
14                         Yes                         Yes
20                         Yes                          No

   Uploaded health records: Extensiveness  \
2                                     4.0
8                                     NaN
10                                    2.0
14                                    NaN
20                                    NaN

   Uploaded health records: Update status  \
2                                     Yes
8                                     NaN
10                                    Yes
14                                    NaN
20                                    NaN

                  Which statement best describes you? Year of birth
2   I am comfortable making my genome sequence dat...   21-29 years
8                                                 NaN          1944
10  I am comfortable making my genome sequence dat...   40-49 years
14  I am comfortable making my genome sequence dat...   50-59 years
20  I am comfortable making my genome sequence dat...   40-49 years

[5 rows x 54 columns]
Respiratory
    Unnamed: 0 profile_id provider_id  \
0            0   hu005023     23andMe
4            4   hu024B5D     23andMe
6            6   hu025CEA     23andMe
10          10   hu034DB1     23andMe
13          13   hu05CA34     23andMe

   Have you ever been diagnosed with any of the following conditions?  \
0         Impacted tooth, Dental cavities, Gallstones
4                      Irritable bowel syndrome (IBS)
6                                     Dental cavities
10  Dental cavities, Temporomandibular joint (TMJ)...
13                    Impacted tooth, Dental cavities

   Other condition not listed here?  \
0                               NaN
4                               NaN
6               Lactose intolerance
10                              NaN
13                              NaN

    PGP Trait & Disease Survey 2012: Digestive System           Timestamp
0   Responses submitted 8/4/2013 21:58:34.  Show r...   8/4/2013 21:58:34
4   Responses submitted 3/2/2014 12:14:23.  Show r...   3/2/2014 12:14:23
6   Responses submitted 3/27/2013 13:26:13.  Show ...  3/27/2013 13:26:13
10  Responses submitted 11/9/2012 8:28:29.  Show r...   11/9/2012 8:28:29
13  Responses submitted 5/9/2013 6:47:43.  Show re...    5/9/2013 6:47:43
Respiratory
    Unnamed: 0 profile_id provider_id  \
0            0   hu005023     23andMe
4            4   hu024B5D     23andMe
6            6   hu025CEA     23andMe
10          10   hu034DB1     23andMe
13          13   hu05CA34     23andMe

   Have you ever been diagnosed with any of the following conditions?  \
0                              Iron deficiency anemia
4                              Iron deficiency anemia
6                              Iron deficiency anemia
10                             Iron deficiency anemia
13                             Iron deficiency anemia

   Other condition not listed here?  \
0                               NaN
4                   hemochromatosis
6                               NaN
10                              NaN
13                              NaN

               PGP Trait & Disease Survey 2012: Blood           Timestamp
0   Responses submitted 8/4/2013 21:55:50.  Show r...   8/4/2013 21:55:50
4   Responses submitted 3/2/2014 12:11:01.  Show r...   3/2/2014 12:11:01
6   Responses submitted 3/27/2013 13:05:12.  Show ...  3/27/2013 13:05:12
10  Responses submitted 11/9/2012 8:25:31.  Show r...   11/9/2012 8:25:31
13  Responses submitted 5/9/2013 6:46:00.  Show re...    5/9/2013 6:46:00
Respiratory
    Unnamed: 0 profile_id provider_id  \
0            0   hu005023     23andMe
5            5   hu024B5D     23andMe
7            7   hu025CEA     23andMe
11          11   hu034DB1     23andMe
14          14   hu05CA34     23andMe

   Have you ever been diagnosed with any of the following conditions?  \
0                                 Lactose intolerance
5   Thyroid nodule(s), Hypothyroidism, Hashimoto's...
7                                     Graves' disease
11                                                NaN
14                                Lactose intolerance

   Other condition not listed here?  \
0                               NaN
5                        polio 1954
7                               NaN
11               Prediabetes type 2
14                              NaN

   PGP Trait & Disease Survey 2012: Endocrine, Metabolic, Nutritional, and Immunity  \
0   Responses submitted 8/4/2013 21:47:10.  Show r...
5   Responses submitted 3/2/2014 12:10:11.  Show r...
7   Responses submitted 3/27/2013 13:04:40.  Show ...
11  Responses submitted 11/9/2012 8:25:11.  Show r...
14  Responses submitted 5/9/2013 6:44:35.  Show re...

             Timestamp
0    8/4/2013 21:47:10
5    3/2/2014 12:10:11
7   3/27/2013 13:04:40
11   11/9/2012 8:25:11
14    5/9/2013 6:44:35
Respiratory
    Unnamed: 0 profile_id provider_id  \
0            0   hu005023     23andMe
5            5   hu024B5D     23andMe
7            7   hu025CEA     23andMe
11          11   hu034DB1     23andMe
14          14   hu05CA34     23andMe

   Have you ever been diagnosed with one of the following conditions?  \
0                                     Cervical cancer
5                                                 NaN
7                                        Colon polyps
11                                   Uterine fibroids
14                                                NaN

   Other condition not listed here?  \
0                               NaN
5                               NaN
7                               NaN
11                              NaN
14                              NaN

             PGP Trait & Disease Survey 2012: Cancers           Timestamp
0   Responses submitted 5/27/2013 11:35:18.  Show ...  5/27/2013 11:35:18
5   Responses submitted 3/2/2014 12:09:13.  Show r...   3/2/2014 12:09:13
7   Responses submitted 3/27/2013 13:03:55.  Show ...  3/27/2013 13:03:55
11  Responses submitted 11/9/2012 8:24:28.  Show r...   11/9/2012 8:24:28
14  Responses submitted 5/9/2013 6:43:24.  Show re...    5/9/2013 6:43:24
Respiratory
    Unnamed: 0 profile_id provider_id  \
0            0   hu005023     23andMe
5            5   hu024B5D     23andMe
7            7   hu025CEA     23andMe
11          11   hu034DB1     23andMe
14          14   hu05CA34     23andMe

   Have you ever been diagnosed with any of the following conditions?  \
0                                                 NaN
5                                                 NaN
7                                                 NaN
11                                                NaN
14                                                NaN

   Other condition not listed here?  \
0                               NaN
5                               NaN
7                               NaN
11                              NaN
14                              NaN

   PGP Trait & Disease Survey 2012: Congenital Traits and Anomalies  \
0   Responses submitted 8/4/2013 22:00:42.  Show r...
5   Responses submitted 3/2/2014 12:21:18.  Show r...
7   Responses submitted 3/27/2013 13:42:52.  Show ...
11  Responses submitted 11/9/2012 8:33:07.  Show r...
14  Responses submitted 5/9/2013 6:50:44.  Show re...

             Timestamp
0    8/4/2013 22:00:42
5    3/2/2014 12:21:18
7   3/27/2013 13:42:52
11   11/9/2012 8:33:07
14    5/9/2013 6:50:44
Respiratory
    Unnamed: 0 profile_id provider_id  \
0            0   hu005023     23andMe
5            5   hu024B5D     23andMe
7            7   hu025CEA     23andMe
11          11   hu034DB1     23andMe
14          14   hu05CA34     23andMe

   Have you ever been diagnosed with one of the following conditions?  \
0                                  Migraine with aura
5                              Restless legs syndrome
7                                                 NaN
11                             Carpal tunnel syndrome
14                                                NaN

   Other condition not listed here?  \
0                               NaN
5                               NaN
7                               NaN
11                              NaN
14                              NaN

      PGP Trait & Disease Survey 2012: Nervous System           Timestamp
0   Responses submitted 8/4/2013 21:55:21.  Show r...   8/4/2013 21:55:21
5   Responses submitted 3/2/2014 12:11:43.  Show r...   3/2/2014 12:11:43
7   Responses submitted 3/27/2013 13:05:31.  Show ...  3/27/2013 13:05:31
11  Responses submitted 11/9/2012 8:26:09.  Show r...   11/9/2012 8:26:09
14  Responses submitted 5/9/2013 6:46:49.  Show re...    5/9/2013 6:46:49
Respiratory
    Unnamed: 0 profile_id provider_id  \
0            0   hu005023     23andMe
4            4   hu024B5D     23andMe
6            6   hu025CEA     23andMe
10          10   hu034DB1     23andMe
13          13   hu05CA34     23andMe

   Have you ever been diagnosed with any of the following conditions?  \
0   Urinary tract infection (UTI), Endometriosis, ...
4        Urinary tract infection (UTI), Ovarian cysts
6                                                 NaN
10       Urinary tract infection (UTI), Ovarian cysts
13                      Urinary tract infection (UTI)

                Other condition not listed here?  \
0                                            NaN
4                                            NaN
6   Exercise-induced hematuria for several years
10                        retroversion of uterus
13                                           NaN

   PGP Trait & Disease Survey 2012: Genitourinary Systems           Timestamp
0   Responses submitted 8/4/2013 21:58:58.  Show r...       8/4/2013 21:58:58
4   Responses submitted 3/2/2014 12:15:08.  Show r...       3/2/2014 12:15:08
6   Responses submitted 3/27/2013 13:27:53.  Show ...      3/27/2013 13:27:53
10  Responses submitted 11/9/2012 8:30:23.  Show r...       11/9/2012 8:30:23
13  Responses submitted 5/9/2013 6:48:14.  Show re...        5/9/2013 6:48:14
Respiratory
    Unnamed: 0 profile_id provider_id  \
0            0   hu005023     23andMe
4            4   hu024B5D     23andMe
6            6   hu025CEA     23andMe
10          10   hu034DB1     23andMe
13          13   hu05CA34     23andMe

   Have you ever been diagnosed with any of the following conditions?  \
0      Chronic tonsillitis, Allergic rhinitis, Asthma
4                                                 NaN
6                                                 NaN
10                                             Asthma
13                 Deviated septum, Allergic rhinitis

                     Other condition not listed here?  \
0                                                 NaN
4                                                 NaN
6   Pseudomonas pneumonia; pleurisy; resolved reac...
10                                                NaN
13                                                NaN

   PGP Trait & Disease Survey 2012: Respiratory System           Timestamp
0   Responses submitted 8/4/2013 21:57:43.  Show r...    8/4/2013 21:57:43
4   Responses submitted 3/2/2014 12:13:44.  Show r...    3/2/2014 12:13:44
6   Responses submitted 3/27/2013 13:13:53.  Show ...   3/27/2013 13:13:53
10  Responses submitted 11/9/2012 8:27:59.  Show r...    11/9/2012 8:27:59
13  Responses submitted 5/9/2013 6:42:07.  Show re...     5/9/2013 6:42:07

In [57]:
for key in comorbidities.keys():
    print(f"{key.upper()}\n{comorbidities[key]}\n")

VISION AND HEARING
Myopia (Nearsightedness), Astigmatism                                                                   20
Myopia (Nearsightedness)                                                                                 5
Myopia (Nearsightedness), Astigmatism, Dry eye syndrome                                                  4
Tinnitus                                                                                                 4
Myopia (Nearsightedness), Astigmatism, Floaters                                                          4
                                                                                                        ..
Age-related macular degeneration, Astigmatism, Color blindness, Dry eye syndrome, Floaters, Tinnitus     1
Hyperopia (Farsightedness), Myopia (Nearsightedness), Astigmatism, Floaters, Tinnitus                    1
Myopia (Nearsightedness), Astigmatism, Dry eye syndrome, Tinnitus                                        1
Myopia (Nearsightedness), Astigmatism, Meniere's disease, Tinnitus                                       1
Infantile, juvenile, and presenile cataract, Myopia (Nearsightedness), Astigmatism                       1
Name: Have you ever been diagnosed with one of the following conditions?, Length: 65, dtype: int64

MUSCULOSKELETAL
Osteoarthritis                                                                                               5
Sciatica                                                                                                     4
Tennis elbow                                                                                                 4
Scoliosis                                                                                                    4
Plantar fasciitis                                                                                            4
                                                                                                            ..
Osteoarthritis, Spinal stenosis, Bone spurs                                                                  1
Flatfeet, Scoliosis                                                                                          1
Osteoarthritis, Bone spurs, Plantar fasciitis                                                                1
Osteoarthritis, Plantar fasciitis, Fibromyalgia, Flatfeet, Postural kyphosis                                 1
Osteoarthritis, Bunions, Fibromyalgia, Scheuermann's kyphosis, Osteoporosis, Postural kyphosis, Scoliosis    1
Name: Have you ever been diagnosed with any of the following conditions?, Length: 70, dtype: int64

SKIN
Acne                                                                                                  12
Dandruff, Skin tags                                                                                    4
Dandruff, Acne                                                                                         4
Allergic contact dermatitis, Skin tags                                                                 4
Dandruff, Skin tags, Acne                                                                              4
                                                                                                      ..
Dandruff, Skin tags, Hair loss (includes female and male pattern baldness), Acne                       1
Dandruff, Allergic contact dermatitis, Hair loss (includes female and male pattern baldness), Acne     1
Eczema                                                                                                 1
Dandruff, Eczema, Allergic contact dermatitis, Rosacea, Skin tags                                      1
Allergic contact dermatitis, Rosacea, Hyperhidrosis (excessive sweating), Acne                         1
Name: Have you ever been diagnosed with any of the following conditions?, Length: 71, dtype: int64

PARTICIPANT SURVEY
Female    61
Male       8
Name: Anatomical sex at birth, dtype: int64

DIGESTIVE
Dental cavities                                                                                                                                                    10
Dental cavities, Canker sores (oral ulcers)                                                                                                                         5
Impacted tooth, Dental cavities, Gingivitis                                                                                                                         5
Impacted tooth, Dental cavities, Gingivitis, Canker sores (oral ulcers)                                                                                             4
Impacted tooth, Dental cavities                                                                                                                                     4
                                                                                                                                                                   ..
Impacted tooth, Dental cavities, Gingivitis, Temporomandibular joint (TMJ) disorder                                                                                 1
Dental cavities, Gingivitis, Nonalcoholic fatty liver disease (NAFLD)                                                                                               1
Impacted tooth, Dental cavities, Gingivitis, Temporomandibular joint (TMJ) disorder, Canker sores (oral ulcers), Peptic ulcer (stomach or duodenum), Gallstones     1
Impacted tooth, Dental cavities, Gingivitis, Temporomandibular joint (TMJ) disorder, Gastroesophageal reflux disease (GERD), Irritable bowel syndrome (IBS)         1
Dental cavities, Gingivitis, Temporomandibular joint (TMJ) disorder                                                                                                 1
Name: Have you ever been diagnosed with any of the following conditions?, Length: 86, dtype: int64

BLOOD
Iron deficiency anemia                                                                                        120
Iron deficiency anemia, Folate deficiency anemia                                                                5
Iron deficiency anemia, Hereditary thrombophilia (includes Factor V Leiden and Prothrombin G20210A)             3
Iron deficiency anemia, Idiopathic thrombocytopenic purpura (ITP)                                               3
Iron deficiency anemia, Other thrombophilia (includes antiphospholipid syndrome)                                3
Iron deficiency anemia, Pernicious anemia (a.k.a. "Addison-Biermer anemia")                                     1
Iron deficiency anemia, Folate deficiency anemia, Other thrombophilia (includes antiphospholipid syndrome)      1
Iron deficiency anemia, Von Willebrand disease                                                                  1
Name: Have you ever been diagnosed with any of the following conditions?, dtype: int64

ENDOCRINE, METABOLIC
High cholesterol (hypercholesterolemia)                                                                                                                                      10
Lactose intolerance                                                                                                                                                           8
High cholesterol (hypercholesterolemia), High triglycerides (hypertriglyceridemia)                                                                                            6
Hypothyroidism                                                                                                                                                                6
Hypothyroidism, Hashimoto's thyroiditis                                                                                                                                       3
Hypothyroidism, High cholesterol (hypercholesterolemia)                                                                                                                       3
Diabetes mellitus, type 2, High cholesterol (hypercholesterolemia), High triglycerides (hypertriglyceridemia)                                                                 3
Polycystic ovary syndrome (PCOS)                                                                                                                                              3
Thyroid nodule(s)                                                                                                                                                             3
Thyroid nodule(s), Hypothyroidism, Hashimoto's thyroiditis                                                                                                                    3
Gout                                                                                                                                                                          2
Thyroid nodule(s), High cholesterol (hypercholesterolemia)                                                                                                                    2
Polycystic ovary syndrome (PCOS), High cholesterol (hypercholesterolemia), High triglycerides (hypertriglyceridemia)                                                          2
Thyroid nodule(s), Hypothyroidism, High cholesterol (hypercholesterolemia)                                                                                                    2
Graves' disease                                                                                                                                                               2
Thyroid nodule(s), Hypothyroidism                                                                                                                                             2
Thyroid nodule(s), Hypothyroidism, Hashimoto's thyroiditis, Diabetes mellitus, type 2, Polycystic ovary syndrome (PCOS)                                                       1
Hypothyroidism, Hashimoto's thyroiditis, Lactose intolerance, High cholesterol (hypercholesterolemia), Gout                                                                   1
Thyroid nodule(s), Hypothyroidism, Growth hormone deficiency, Polycystic ovary syndrome (PCOS)                                                                                1
Hypothyroidism, Gout, Porphyria                                                                                                                                               1
Thyroid nodule(s), Hashimoto's thyroiditis                                                                                                                                    1
Diabetes mellitus, type 2, Lactose intolerance, Gout                                                                                                                          1
Hypothyroidism, Lactose intolerance, High cholesterol (hypercholesterolemia), High triglycerides (hypertriglyceridemia)                                                       1
High cholesterol (hypercholesterolemia), High triglycerides (hypertriglyceridemia), Gout                                                                                      1
Thyroid nodule(s), Hypothyroidism, Hashimoto's thyroiditis, Diabetes mellitus, type 2, High cholesterol (hypercholesterolemia), High triglycerides (hypertriglyceridemia)     1
Diabetes mellitus, type 2                                                                                                                                                     1
Hypothyroidism, Polycystic ovary syndrome (PCOS), High triglycerides (hypertriglyceridemia)                                                                                   1
Thyroid nodule(s), Hypothyroidism, Hashimoto's thyroiditis, High cholesterol (hypercholesterolemia)                                                                           1
Polycystic ovary syndrome (PCOS), Lactose intolerance                                                                                                                         1
Thyroid nodule(s), High cholesterol (hypercholesterolemia), High triglycerides (hypertriglyceridemia)                                                                         1
Thyroid nodule(s), Graves' disease, Hypothyroidism, Hashimoto's thyroiditis                                                                                                   1
Thyroid nodule(s), Lactose intolerance                                                                                                                                        1
Diabetes mellitus, type 2, High cholesterol (hypercholesterolemia)                                                                                                            1
Thyroid nodule(s), Hypothyroidism, Hashimoto's thyroiditis, Hemochromatosis                                                                                                   1
Thyroid nodule(s), Hypothyroidism, Polycystic ovary syndrome (PCOS), High cholesterol (hypercholesterolemia), High triglycerides (hypertriglyceridemia)                       1
Hypothyroidism, Diabetes mellitus, type 2, High cholesterol (hypercholesterolemia)                                                                                            1
Hashimoto's thyroiditis                                                                                                                                                       1
Name: Have you ever been diagnosed with any of the following conditions?, dtype: int64

CANCERS
Non-melanoma skin cancer                              8
Colon polyps                                          7
Uterine fibroids                                      7
Cervical cancer                                       2
Colon polyps, Non-melanoma skin cancer                2
Lipoma                                                2
Thyroid cancer                                        1
Non-melanoma skin cancer, Uterine fibroids            1
Colon polyps, Uterine fibroids                        1
Breast cancer                                         1
Uterine fibroids, Kidney cancer                       1
Non-melanoma skin cancer, Endometrial cancer          1
Cervical cancer, Thyroid cancer                       1
Lipoma, Uterine fibroids                              1
Colon polyps, Cervical cancer                         1
Colon polyps, Non-melanoma skin cancer, Lipoma        1
Cervical cancer, Uterine fibroids                     1
Non-melanoma skin cancer, Lipoma, Uterine fibroids    1
Endometrial cancer                                    1
Melanoma, Non-melanoma skin cancer                    1
Name: Have you ever been diagnosed with one of the following conditions?, dtype: int64

CONGENITAL TRAITS
Ehlers-Danlos syndrome                                                                           7
Congenital heart defect                                                                          3
Congenital heart defect, Ehlers-Danlos syndrome                                                  2
Developmental dysplasia of the hip                                                               2
Hypospadias                                                                                      1
Spina bifida                                                                                     1
Congenital clubfoot (equinovarus)                                                                1
Developmental dysplasia of the hip, Congenital clubfoot (equinovarus), Ehlers-Danlos syndrome    1
Polycystic kidney disease                                                                        1
Name: Have you ever been diagnosed with any of the following conditions?, dtype: int64

NERVOUS
Migraine with aura                                                                                                                                                             7
Carpal tunnel syndrome                                                                                                                                                         7
Migraine with aura, Migraine without aura                                                                                                                                      6
Migraine without aura                                                                                                                                                          6
Restless legs syndrome                                                                                                                                                         4
Restless legs syndrome, Carpal tunnel syndrome                                                                                                                                 3
Migraine without aura, Carpal tunnel syndrome                                                                                                                                  3
Migraine without aura, Trigeminal neuralgia                                                                                                                                    2
Trigeminal neuralgia                                                                                                                                                           2
Restless legs syndrome, Migraine with aura                                                                                                                                     2
Chronic tension headaches (15+ days per month, at least 6 months)                                                                                                              2
Epilepsy                                                                                                                                                                       2
Multiple sclerosis (MS), Migraine with aura                                                                                                                                    2
Other peripheral neuropathy                                                                                                                                                    2
Bell's palsy, Other peripheral neuropathy                                                                                                                                      1
Cluster headaches                                                                                                                                                              1
Muscular dystrophy                                                                                                                                                             1
Essential tremor, Cluster headaches, Epilepsy, Carpal tunnel syndrome, Other peripheral neuropathy                                                                             1
Restless legs syndrome, Migraine without aura, Other peripheral neuropathy                                                                                                     1
Restless legs syndrome, Migraine with aura, Migraine without aura                                                                                                              1
Chronic tension headaches (15+ days per month, at least 6 months), Migraine with aura, Migraine without aura, Other peripheral neuropathy                                      1
Restless legs syndrome, Chronic tension headaches (15+ days per month, at least 6 months)                                                                                      1
Narcolepsy                                                                                                                                                                     1

In [60]:
demo_surveys = '/Users/jerenolsen/Desktop/PGP_Harvard_data/Surveys/All Combined/Participant Survey'
demo_ehr = '/Users/jerenolsen/Desktop/PGP_Harvard_data/EHRS/All Combined/demographics'
demo_surveys  = pd.read_csv(demo_surveys, delimiter = '\t')
demo_ehr = pd.read_csv(demo_ehr, delimiter = '\t')

In [62]:
demo_surveys.columns.tolist()

['Unnamed: 0',
 'profile_id',
 'provider_id',
 'Anatomical sex at birth',
 'Are all your enrolled relatives linked to your PGP profile?',
 'Blood sample',
 'Disease/trait: Diagnosis',
 'Disease/trait: Documentation',
 'Disease/trait: Documentation description',
 'Disease/trait: Genetic confirmation',
 'Disease/trait: Onset',
 'Disease/trait: Rarity',
 'Disease/trait: Relative enrollment',
 'Disease/trait: Severity',
 'Do you have a severe genetic disease or rare genetic trait? If so, you can add a description for your public profile.',
 'Enrolled relatives [Aunts/Uncles]',
 'Enrolled relatives [Children]',
 'Enrolled relatives [Cousins or more distant]',
 'Enrolled relatives [Grandchildren]',
 'Enrolled relatives [Grandparents]',
 'Enrolled relatives [Half-siblings]',
 'Enrolled relatives [Monozygotic / Identical twins]',
 'Enrolled relatives [Nephews/Nieces]',
 'Enrolled relatives [Not genetically related (e.g. husband/wife)]',
 'Enrolled relatives [Parents]',
 'Enrolled relatives [Siblings / Fraternal twins]',
 'Enrollment of older individuals',
 'Enrollment of parents',
 'Enrollment of relatives',
 'Have you uploaded genetic data to your PGP participant profile?',
 'Have you uploaded health record data using our Google Health or Microsoft Healthvault interfaces?',
 'Have you used the PGP web interface to record a designated proxy?',
 'Maternal grandfather: Country of origin',
 'Maternal grandfather: Race/ethnicity',
 'Maternal grandmother: Country of origin',
 'Maternal grandmother: Race/ethnicity',
 'Microbiome samples',
 'Month of birth',
 'PGP Participant Survey',
 'Paternal grandfather: Country of origin',
 'Paternal grandfather: Race/ethnicity',
 'Paternal grandmother: Country of origin',
 'Paternal grandmother: Race/ethnicity',
 'Race/ethnicity',
 'Saliva sample',
 'Severe disease or rare genetic trait',
 'Sex/Gender',
 'Timestamp',
 'Tissue samples from autopsy',
 'Tissue samples from surgery',
 'Uploaded health records: Extensiveness',
 'Uploaded health records: Update status',
 'Which statement best describes you?',
 'Year of birth']

In [64]:
demo_surveys = demo_surveys[['profile_id','Race/ethnicity','Maternal grandfather: Country of origin','Maternal grandmother: Country of origin','Paternal grandfather: Country of origin','Paternal grandmother: Country of origin']]

In [67]:
demo_surveys.head(50)

,profile_id,Race/ethnicity,Maternal grandfather: Country of origin,Maternal grandmother: Country of origin,Paternal grandfather: Country of origin,Paternal grandmother: Country of origin
0,hu00147A,"American Indian / Alaska Native, White",United States,United States,United States,United States
1,hu002B3C,White,United States,United States,United States,United States
2,hu005023,White,Other / don't know / no response,Other / don't know / no response,Other / don't know / no response,Other / don't know / no response
3,hu00698E,White,United States,United States,United States,United States
4,hu011C57,White,Netherlands,Netherlands,Hungary,Hungary
5,hu016B28,White,Russian Federation,United States,Poland,Poland
6,hu0199C8,White,United States,United States,United States,United States
7,hu019BBA,White,United States,United States,United States,United States
8,hu024B5D,White,United States,United States,United States,Norway
9,hu0257DA,White,United States,United States,United States,United States
10,hu025CEA,White,United States,United States,United States,United States
11,hu026DEA,White,Germany,Germany,Italy,Argentina
12,hu029DBB,White,United States,United States,United States,United States
13,hu032C04,White,United States,United States,United States,United States
14,hu034DB1,White,United States,United States,United States,United States
15,hu0369A1,White,United States,United States,United States,United States
16,hu03E466,White,Italy,Italy,United States,United States
17,hu0471B4,White,Other / don't know / no response,United States,Spain,Spain
18,hu0486D6,White,Russian Federation,Poland,Latvia,Latvia
19,hu0515BA,White,Poland,Poland,Poland,Poland
20,hu05CA34,White,Ukraine,Ukraine,Ukraine,Ukraine
21,hu05F442,White,United States,United States,United States,United States
22,hu05FD49,White,United States,United States,Italy,United States
23,hu065B67,White,Czech Republic,Austria,Poland,Poland
24,hu066C78,White,Bulgaria,Bulgaria,Bulgaria,Bulgaria
25,hu0684DB,White,Germany,Germany,Germany,Poland
26,hu08334F,White,United States,United States,United States,United States
27,hu0878AF,White,United States,Canada,United States,United States
28,hu092771,White,United States,United States,United States,United States
29,hu09D626,White,Other / don't know / no response,Croatia,Other / don't know / no response,Other / don't know / no response
30,hu0A4518,White,United States,United States,United States,United States
31,hu0A6570,White,United States,United States,United States,United States
32,hu0B4CF6,"American Indian / Alaska Native, Hispanic or L...",United States,United States,Netherlands,United States
33,hu0B51B8,Black or African American,United States,United States,United States,United States
34,hu0B9C47,White,United States,United States,United States,United States
35,hu0C0779,White,Other / don't know / no response,Other / don't know / no response,Germany,Germany
36,hu0C1563,White,United States,Canada,Canada,Canada
37,hu0C8573,White,United States,United States,United States,United States
38,hu0D2DBE,White,Lebanon,Denmark,Syrian Arab Republic,Norway
39,hu0DEE68,White,United States,Germany,United States,United States
40,hu0E64A1,White,Italy,Austria,Other / don't know / no response,Other / don't know / no response
41,hu0E7AAF,White,Other / don't know / no response,United States,United States,United States
42,hu0FDE6C,White,United States,United States,United States,United States
43,hu101457,White,United Kingdom,United Kingdom,United Kingdom,United Kingdom
44,hu101EF8,White,United States,United States,United States,United States
45,hu10771F,White,Spain,Spain,Australia,Australia
46,hu11603C,White,United States,Other / don't know / no response,United States,Other / don't know / no response
47,hu117D1E,White,Poland,Poland,Poland,Poland
48,hu1187FF,White,United States,United States,United States,United States
49,hu11DF5B,White,United States,United States,Canada,Canada

# Hypertension

In [8]:
survey_circ_file = '/Users/jerenolsen/Desktop/PGP_Harvard_data/Surveys/All Combined/Circulatory'
circ_df = pd.read_csv(survey_circ_file, delimiter = '\t')
circ_df.rename(columns = {'Have you ever been diagnosed with one of the following conditions?':'conditions'}, inplace =True)
circ_df.replace(np.nan,'',regex=True, inplace=True)

In [11]:
hyper_df = circ_df[circ_df['conditions'].str.contains('Hyper')]
hyper_df`

,Unnamed: 0,profile_id,provider_id,conditions,Other condition not listed here?,PGP Trait & Disease Survey 2012: Circulatory System,Timestamp
10,10,hu034DB1,23andMe,Hypertension,,Responses submitted 11/9/2012 8:27:41. Show r...,11/9/2012 8:27:41
15,15,hu05FD49,23andMe,"Hypertension, Varicose veins, Varicocele",Inverted T,Responses submitted 10/19/2012 15:55:22. Show...,10/19/2012 15:55:22
20,20,hu0878AF,23andMe,Hypertension,,Responses submitted 3/8/2016 11:07:03. Show r...,3/8/2016 11:07:03
25,25,hu0B9C47,23andMe,"Hypertension, Varicocele",,Responses submitted 9/8/2015 18:49:41. Show r...,9/8/2015 18:49:41
33,33,hu101EF8,23andMe,"Hypertension, Bundle branch block",,Responses submitted 9/4/2015 23:40:18. Show r...,9/4/2015 23:40:18
...,...,...,...,...,...,...,...
648,648,huCBDC6D,CG,"Hypertension, Hemorrhoids",,Responses submitted 11/29/2012 23:52:03. Show...,11/29/2012 23:52:03
650,650,huCCD063,CG,Hypertension,,Responses submitted 3/27/2013 12:24:39. Show ...,3/27/2013 12:24:39
663,663,huDBF9DD,CG,Hypertension,,Responses submitted 3/27/2013 14:37:05. Show ...,3/27/2013 14:37:05
672,672,huEBD467,CG,Hypertension,,Responses submitted 12/15/2012 17:59:53. Show...,12/15/2012 17:59:53
675,675,huF160AA,CG,"Hypertension, Hemorrhoids",,Responses submitted 3/5/2014 20:57:49. Show r...,3/5/2014 20:57:49

In [ ]:
hyper_ids = hyper_df['profile_ids'].to_list()a

# Osteoarthritis

In [28]:
survey_musc_file = '/Users/jerenolsen/Desktop/PGP_Harvard_data/Surveys/All Combined/Musculoskeletal'
musc_df = pd.read_csv(survey_musc_file, delimiter = '\t')
musc_df.rename(columns = {'Have you ever been diagnosed with any of the following conditions?':'conditions'}, inplace =True)
musc_df.replace(np.nan,'',regex=True, inplace=True) 
musc_df.head()

,Unnamed: 0,profile_id,provider_id,conditions,Other condition not listed here?,PGP Trait & Disease Survey 2012: Musculoskeletal System and Connective Tissue,Timestamp
0,0,hu005023,23andMe,Sciatica,,Responses submitted 8/4/2013 22:00:19. Show r...,8/4/2013 22:00:19
1,1,hu00698E,23andMe,,,Responses submitted 10/8/2014 16:50:29. Show ...,10/8/2014 16:50:29
2,2,hu011C57,23andMe,,,Responses submitted 10/13/2012 1:34:00. Show ...,10/13/2012 1:34:00
3,3,hu016B28,23andMe,"Spinal stenosis, Achilles tendonitis, Trigger ...",Calcific Tendonitis,Responses submitted 10/25/2012 13:18:55. Show...,10/25/2012 13:18:55
4,4,hu024B5D,23andMe,"Osteoarthritis, Bone spurs, Plantar fasciitis",polio 1954,Responses submitted 3/2/2014 12:22:15. Show r...,3/2/2014 12:22:15

In [35]:
osteo_df = musc_df[musc_df['conditions'].str.contains('Osteoar')]

In [36]:
osteo_df

,Unnamed: 0,profile_id,provider_id,conditions,Other condition not listed here?,PGP Trait & Disease Survey 2012: Musculoskeletal System and Connective Tissue,Timestamp
4,4,hu024B5D,23andMe,"Osteoarthritis, Bone spurs, Plantar fasciitis",polio 1954,Responses submitted 3/2/2014 12:22:15. Show r...,3/2/2014 12:22:15
22,22,hu09D626,23andMe,"Osteoarthritis, Spinal stenosis, Frozen should...",Ehlers-Danlos Syndrome,Responses submitted 3/14/2013 12:40:47. Show ...,3/14/2013 12:40:47
33,33,hu11603C,23andMe,"Osteoarthritis, Chondromalacia patella (CMP), ...",,Responses submitted 11/21/2012 11:26:32. Show...,11/21/2012 11:26:32
37,37,hu1213DA,23andMe,Osteoarthritis,I took glucosamine and chondroitin to alleviat...,Responses submitted 7/16/2013 9:54:53. Show r...,7/16/2013 9:54:53
39,39,hu1287DA,23andMe,"Osteoarthritis, Bone spurs",,Responses submitted 12/11/2014 20:42:32. Show...,12/11/2014 20:42:32
...,...,...,...,...,...,...,...
626,626,huA5BEB9,CG,"Osteoarthritis, Frozen shoulder, Plantar fasci...",,Responses submitted 9/13/2014 15:52:02. Show ...,9/13/2014 15:52:02
639,639,huBA30D4,CG,"Osteoarthritis, Spinal stenosis, Frozen shoulder",,Responses submitted 10/16/2012 20:13:32. Show...,10/16/2012 20:13:32
640,640,huBAAC98,CG,"Osteoarthritis, Flatfeet",,Responses submitted 3/28/2014 14:59:21. Show ...,3/28/2014 14:59:21
663,663,huD649F1,CG,"Osteoarthritis, Bunions, Fibromyalgia, Scheuer...",,Responses submitted 4/28/2014 21:06:40. Show ...,4/28/2014 21:06:40
685,685,huF83462,CG,"Osteoarthritis, Frozen shoulder",,Responses submitted 5/4/2014 1:49:07. Show re...,5/4/2014 1:49:07

In [37]:
print(len(osteo_df['profile_id'].unique()))

91